const data = {
  code: 200,
  msg: "성공하였습니다.",
  result: {
    mapListBanner: {
      bannerList: [],
      config: {
        isLoop: true,
        bannerExposureStartPoint: 3,
        bannerExposureGapCount: 10,
      },
    },
    roomList: [
      {
        seq: 52694280,
        id: "68ba7e8e89baeb422ca2c4c9",
        roomTypeName: "오피스텔 • 단기",
        randomLocation: {
          lat: 37.497282,
          lng: 126.729721,
        },
        complexName: "스카이씨티",
        roomTitle:
          "ㅇ부평시장역 인근ㅇ신축 첫입주ㅇ빠르게 없어지고있어요ㅇ인기쓰리룸ㅇ문e환영ㅇ",
        roomDesc: "저층, 77.22m², 관리비 8만",
        priceTypeName: "월세",
        priceTitle: "300/135",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/ldjjPGKt-d0VwcXwjtRYH",
          "https://d1774jszgerdmk.cloudfront.net/512/sItuz3rsZoS4FfvKSrlpX",
          "https://d1774jszgerdmk.cloudfront.net/512/YA_rBV3C9jYT_7Zx75BBN",
          "https://d1774jszgerdmk.cloudfront.net/512/QllNFRXablSXbJyLdGY1m",
          "https://d1774jszgerdmk.cloudfront.net/512/0cUH1gPkLiVKJuZS4W8Yu",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 49163815,
        id: "67bec76e032b2b12d53d0e0f",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.484733,
          lng: 126.723027,
        },
        complexName: "부평역해링턴플레이스",
        roomTitle:
          "2룸.최저가.냉장고.세탁기.에어컨.인덕션.넓은드레스룸.첫입주..전입불가",
        roomDesc: "고층, 59.94m², 관리비 확인 불가",
        priceTypeName: "월세",
        priceTitle: "2000/110",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/aUDSChmUmWyR9CmIyDeok",
          "https://d1774jszgerdmk.cloudfront.net/512/hkr-k68k4gjH7A8QXIS0s",
          "https://d1774jszgerdmk.cloudfront.net/512/F4Edpn9XAtixIRWnQaRUu",
          "https://d1774jszgerdmk.cloudfront.net/512/YrZKb3ojzC_6W8BfmWoQP",
          "https://d1774jszgerdmk.cloudfront.net/512/CQOMUnrRVgq4UuMcmWsgH",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52830620,
        id: "68c4dedb37a1c25a60523061",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.490749,
          lng: 126.727723,
        },
        complexName: "노블렌스",
        roomTitle: "실매물사진 빠른입주가능 전입신고가능 풀옵션복층형오피스텔",
        roomDesc: "중층, 20.96m², 관리비 10만",
        priceTypeName: "월세",
        priceTitle: "300/52",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/sl728OavphwYjG9iUu25L",
          "https://d1774jszgerdmk.cloudfront.net/512/Iv3ofLNkciA13Fpa2fIXg",
          "https://d1774jszgerdmk.cloudfront.net/512/JIrEhPoaT9Cy5JRTYHRx-",
          "https://d1774jszgerdmk.cloudfront.net/512/r-FK3vOZE-D3rAlIcfXpG",
          "https://d1774jszgerdmk.cloudfront.net/512/TaBk_g22QEZ48iT0oj7CW",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52953104,
        id: "68ce0f2b88a92d143a578ada",
        roomTypeName: "오피스텔 • 단기",
        randomLocation: {
          lat: 37.500584,
          lng: 126.722331,
        },
        complexName: "부평대우마이빌",
        roomTitle: "OㅅO 반려동물협의.수납 최고.큰방.오피스텔.구청역5분.빌트인",
        roomDesc: "15층, 32.57m², 관리비 9만",
        priceTypeName: "월세",
        priceTitle: "100/65",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/096d19f3-59d5-4196-9e5d-ecad3aa43c03",
          "https://d1774jszgerdmk.cloudfront.net/512/a7b6b754-0cc8-46af-8a9f-7536d08329e4",
          "https://d1774jszgerdmk.cloudfront.net/512/e54ba5d0-f891-4096-8681-1d55f2939a71",
          "https://d1774jszgerdmk.cloudfront.net/512/b6f7d5ad-bb23-4c5d-8656-379ae0729450",
          "https://d1774jszgerdmk.cloudfront.net/512/315f35cd-f626-49f2-8473-c5ac81160fdd",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52979284,
        id: "68d0cd8f5203a224bdc72baa",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.464487,
          lng: 126.679494,
        },
        complexName: "디에이리베로",
        roomTitle: "+주안역 뛰어서 30초+ 풀옵션 주차가능 오피스텔",
        roomDesc: "11층, 28.5m², 관리비 5만",
        priceTypeName: "월세",
        priceTitle: "70/55",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/csEY5ukzAS0ywEKazaylN",
          "https://d1774jszgerdmk.cloudfront.net/512/76EczQ5mH48rqOCs8fLpD",
          "https://d1774jszgerdmk.cloudfront.net/512/pgVDo7F0N2vVCQAyV6wmK",
          "https://d1774jszgerdmk.cloudfront.net/512/a-n1F4-UxBMQjAXZkE_cL",
          "https://d1774jszgerdmk.cloudfront.net/512/RrDbInt95cBb25NFAuiXO",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9084,
        dongName: "주안동",
      },
      {
        seq: 52987587,
        id: "68d0f55126b30c12b08176f0",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.490039,
          lng: 126.753279,
        },
        complexName: "금강리빙스텔",
        roomTitle:
          "송내역 바로앞  풀옵션 오피스텔  단층  이중샤시 대로변위치 이사협의",
        roomDesc: "11층, 27.6m², 관리비 9만",
        priceTypeName: "월세",
        priceTitle: "500/37",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/9H2M-FCuWKj1zGxtTfDzf",
          "https://d1774jszgerdmk.cloudfront.net/512/rYJsu_7xRAKHN5MmcHyZA",
          "https://d1774jszgerdmk.cloudfront.net/512/3ENXnulcgxJ5--qUEkqtB",
          "https://d1774jszgerdmk.cloudfront.net/512/o8Rc-cGk8PdGi-8NXNVQ-",
          "https://d1774jszgerdmk.cloudfront.net/512/qDIwE_eG31ufPJ8txa51k",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 7308,
        dongName: "상동",
      },
      {
        seq: 52940484,
        id: "68cce0b9c1cbae5464cb73ce",
        roomTypeName: "오피스텔 • 단기",
        randomLocation: {
          lat: 37.463272,
          lng: 126.690152,
        },
        complexName: "해마루더펠리체",
        roomTitle: "신축  프리미엄 복층원룸",
        roomDesc: "8층, 30.81m², 관리비 9만",
        priceTypeName: "월세",
        priceTitle: "300/55",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/lH6sUjBJb1BEJq7xkq2bs",
          "https://d1774jszgerdmk.cloudfront.net/512/xseKTotA4NNHSkxVsWCTL",
          "https://d1774jszgerdmk.cloudfront.net/512/tJdjbvojB_6u0vvplty7Y",
          "https://d1774jszgerdmk.cloudfront.net/512/qMA095LYrXh4bGpGUk0nK",
          "https://d1774jszgerdmk.cloudfront.net/512/9ALpULTS-yR0gdsWfnKoZ",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9084,
        dongName: "주안동",
      },
      {
        seq: 51953300,
        id: "6882fc4dfffc3303927bb5c8",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.465935,
          lng: 126.679639,
        },
        complexName: "더로프트",
        roomTitle: "신축 쓰리룸 복층 첫입주",
        roomDesc: "6층, 83.11m², 관리비 15만",
        priceTypeName: "월세",
        priceTitle: "3000/120",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/jZuNz0jVW-54pRcJCutnm",
          "https://d1774jszgerdmk.cloudfront.net/512/coHKt-xzH9nPKJg_fm0U1",
          "https://d1774jszgerdmk.cloudfront.net/512/BsKT6pkr6NtS8YWb9pzNU",
          "https://d1774jszgerdmk.cloudfront.net/512/7bUtmSRi-4hWWQxo4dgHi",
          "https://d1774jszgerdmk.cloudfront.net/512/Ggf8jXj_24bFVu7T6xDxC",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9084,
        dongName: "주안동",
      },
      {
        seq: 52655109,
        id: "68b7f2e8c5d21f76734d188e",
        roomTypeName: "오피스텔 • 단기",
        randomLocation: {
          lat: 37.490749,
          lng: 126.727723,
        },
        complexName: "노블렌스",
        roomTitle: "ll 단기가능 ll 반려동물가능 ll 복층 ll 허위x ll",
        roomDesc: "10층, 19.8m², 관리비 7만",
        priceTypeName: "월세",
        priceTitle: "80/48",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/-5D189BsoIYFC-1kk5-_U",
          "https://d1774jszgerdmk.cloudfront.net/512/5MOedvwB_VE_F4nnNfKko",
          "https://d1774jszgerdmk.cloudfront.net/512/AKWbyge7oOiyNe_MAhO8T",
          "https://d1774jszgerdmk.cloudfront.net/512/cGo2k5lN2MlVUZLD-AIPH",
          "https://d1774jszgerdmk.cloudfront.net/512/gXT1VHr_jvO6736GG4qSk",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52623175,
        id: "68b64caff5a5663b98a6c5f8",
        roomTypeName: "오피스텔 • 단기",
        randomLocation: {
          lat: 37.489705,
          lng: 126.728623,
        },
        complexName: "부평현대더로프트",
        roomTitle: "NEW.부평대표복층/ 빌트인풀옵션/ 주차가능",
        roomDesc: "중층, 29.08m², 관리비 7만",
        priceTypeName: "월세",
        priceTitle: "100/60",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/rEpI0hUe2Wb8R-iynOhuK",
          "https://d1774jszgerdmk.cloudfront.net/512/LzOWss0M7DbSBYrSczMJk",
          "https://d1774jszgerdmk.cloudfront.net/512/2UvcwNCGr32VzluWlOoDN",
          "https://d1774jszgerdmk.cloudfront.net/512/G7u5YNsXnsYBXdzP69cgY",
          "https://d1774jszgerdmk.cloudfront.net/512/w3R6_8HznuPqoTLWwS5mR",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52560673,
        id: "68b10d42de189d0f790ac58f",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.484733,
          lng: 126.723027,
        },
        complexName: "부평역해링턴플레이스",
        roomTitle: "전입안됨 투룸 풀옵션 첫입주 이사 아무때나",
        roomDesc: "고층, 59.94m², 관리비 확인 불가",
        priceTypeName: "월세",
        priceTitle: "2000/115",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/X9zELnzvHbxh3l3G_GwDg",
          "https://d1774jszgerdmk.cloudfront.net/512/Ao5jtE1_kIDLxSA_33sEY",
          "https://d1774jszgerdmk.cloudfront.net/512/87kjNs0NT5jXFrczxthLl",
          "https://d1774jszgerdmk.cloudfront.net/512/QjTC2uzFueDYzu6P26Bin",
          "https://d1774jszgerdmk.cloudfront.net/512/1s7OpqEos7sULBK93rjUR",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52980556,
        id: "68d0d3060e1ce2296da37e59",
        roomTypeName: "오피스텔 • 단기",
        randomLocation: {
          lat: 37.469132,
          lng: 126.692194,
        },
        complexName: "늘푸른파크",
        roomTitle: "ㅇ간석동알짜매물ㅇ컨디션 좋은 쓰리룸으로 바로 보기 가능ㅇ",
        roomDesc: "고층, 69.19m², 관리비 9만",
        priceTypeName: "월세",
        priceTitle: "100/60",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/z8lzCc6w5HBLbu2bfJOCX",
          "https://d1774jszgerdmk.cloudfront.net/512/1iMHP8Dz3QU7PGN7tiyR7",
          "https://d1774jszgerdmk.cloudfront.net/512/eiKZ9K1dIeVYTHMrVk6hg",
          "https://d1774jszgerdmk.cloudfront.net/512/tQS6S2W8BZpbYPyrTpOff",
          "https://d1774jszgerdmk.cloudfront.net/512/cun3-EaTO4_wHpM79AoNN",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9127,
        dongName: "간석동",
      },
      {
        seq: 52887433,
        id: "68c9223e607f2371bc7d7cac",
        roomTypeName: "오피스텔 • 단기",
        randomLocation: {
          lat: 37.490846,
          lng: 126.722023,
        },
        complexName: "더시티뷰(생활숙박시설)",
        roomTitle: "ll 단기가능 ll 부평역1분 ll 신축 ll 허위x ll",
        roomDesc: "15층, 18.14m², 관리비 7만",
        priceTypeName: "월세",
        priceTitle: "70/53",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/0yaxxxjC6w-eFa0swRhEc",
          "https://d1774jszgerdmk.cloudfront.net/512/fcMg8ck1oJ_oSa5UPNWxM",
          "https://d1774jszgerdmk.cloudfront.net/512/PZry3NMumT9Joo5Oso3K3",
          "https://d1774jszgerdmk.cloudfront.net/512/Nij7lrorSis4BQTnKGlli",
          "https://d1774jszgerdmk.cloudfront.net/512/3wH4Fb52DYw4YHASxg_dg",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52590710,
        id: "68b466ec57c801374efeea08",
        roomTypeName: "오피스텔 • 단기",
        randomLocation: {
          lat: 37.496674,
          lng: 126.729918,
        },
        complexName: "라일플로리스",
        roomTitle: "oo9월업데이트o단기o풀옵션oo저렴한방oo공실24시항시대기",
        roomDesc: "8층, 21.06m², 관리비 5만",
        priceTypeName: "월세",
        priceTitle: "60/47",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/rU0AER_u9UGc5uXNPyQkb",
          "https://d1774jszgerdmk.cloudfront.net/512/vEIEU34dU-4cM5DC5RcLj",
          "https://d1774jszgerdmk.cloudfront.net/512/jO6_EyMk3Fu7rfNEl2uw5",
          "https://d1774jszgerdmk.cloudfront.net/512/kLBnbydY7O2xYP_d3eg4a",
          "https://d1774jszgerdmk.cloudfront.net/512/chgllw7ZoGN_dUz-AGSOS",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52812181,
        id: "68c381c4ec390f7ccf688fc3",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.46614,
          lng: 126.70895,
        },
        complexName: "JH타워Ⅲ",
        roomTitle: "신축급 쓰리룸",
        roomDesc: "3층, 59.91m², 관리비 8만",
        priceTypeName: "월세",
        priceTitle: "2000/80",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/71648687-25ce-4887-8343-fc51978e8fbe",
          "https://d1774jszgerdmk.cloudfront.net/512/53154c23-ec41-438f-aa99-7562e111cf2b",
          "https://d1774jszgerdmk.cloudfront.net/512/4de260ae-fcd7-4aff-b4f0-597d396f59ed",
          "https://d1774jszgerdmk.cloudfront.net/512/1d435142-a6b2-4952-93dd-1e45cc544a29",
          "https://d1774jszgerdmk.cloudfront.net/512/bbabb945-9fe5-431f-9571-a74ea1aafb4b",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9127,
        dongName: "간석동",
      },
      {
        seq: 52590720,
        id: "68b4676ecb5f6b3b2526d3e3",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.490846,
          lng: 126.722023,
        },
        complexName: "더시티뷰(생활숙박시설)",
        roomTitle: "oo9월업데이트o단기o풀옵션oo저렴한방oo공실24시항시대기",
        roomDesc: "7층, 18.14m², 관리비 7만",
        priceTypeName: "월세",
        priceTitle: "70/53",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/Tj9f91ONUMVj5P-zgix-a",
          "https://d1774jszgerdmk.cloudfront.net/512/loMjNc0TUyDAn4ozw3bdu",
          "https://d1774jszgerdmk.cloudfront.net/512/KnpGzA-Y2cZNOsCgpTQf9",
          "https://d1774jszgerdmk.cloudfront.net/512/_SQV7ZYGID7xkZ5qFSqd-",
          "https://d1774jszgerdmk.cloudfront.net/512/4IkjxW-FsQZ1gQkkx0EDZ",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 48587837,
        id: "6794b0686cbd0f1fb454c2a3",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.484733,
          lng: 126.723027,
        },
        complexName: "부평역해링턴플레이스",
        roomTitle:
          "전입불가 .방2넓은거실.첫입주.풀옵션 동수역부평역도보가능대단지",
        roomDesc: "고층, 59.94m², 관리비 17만",
        priceTypeName: "월세",
        priceTitle: "2500/105",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/i7XeRBWIVnZCgiJMKmS_V",
          "https://d1774jszgerdmk.cloudfront.net/512/6E9-VaQMtBo8jrB4qvrjU",
          "https://d1774jszgerdmk.cloudfront.net/512/_wz-ca7HjQpWUNM3Sn1D5",
          "https://d1774jszgerdmk.cloudfront.net/512/2wMolBmiEyJuPUoAoDVCk",
          "https://d1774jszgerdmk.cloudfront.net/512/11wTFl1h9_2uO0xepu2Ik",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52799252,
        id: "68c2641b89876d175b1c999d",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.49799,
          lng: 126.723536,
        },
        complexName: "부평한라비발디",
        roomTitle:
          "단기가능,연장기능,신축풀옵션오피스텔,부평시장역초역세권,주차100",
        roomDesc: "중층, 22.26m², 관리비 8만",
        priceTypeName: "월세",
        priceTitle: "300/55",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/YLhlo0gPAhGjsLn_UYlug",
          "https://d1774jszgerdmk.cloudfront.net/512/eFjGVhkeLZH3i_MkhEcGk",
          "https://d1774jszgerdmk.cloudfront.net/512/xIKUbqGnkr_gfMib4hbkf",
          "https://d1774jszgerdmk.cloudfront.net/512/HtbgyQ9czIVhWyK9WfrYu",
          "https://d1774jszgerdmk.cloudfront.net/512/C2QFqhs_1snvuYSvDBpfJ",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 51577256,
        id: "68677752e6541678c110bce8",
        roomTypeName: "오피스텔 • 단기",
        randomLocation: {
          lat: 37.463937,
          lng: 126.688433,
        },
        complexName: "월드빌",
        roomTitle: "애견가능 전입가능 넓은방 말이 필요없는 최고 컨디션",
        roomDesc: "3층, 29.18m², 관리비 5.2만",
        priceTypeName: "월세",
        priceTitle: "70/55",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/YniC_7Yrt-Qjy5rzDkzA4",
          "https://d1774jszgerdmk.cloudfront.net/512/Uu3eGklcy9zMWunVdaP1N",
          "https://d1774jszgerdmk.cloudfront.net/512/UOIvY6twWFXxMam1Cn5Na",
          "https://d1774jszgerdmk.cloudfront.net/512/82bGL0DPS7JT5F7q4_e1j",
          "https://d1774jszgerdmk.cloudfront.net/512/po8P7q8a724WmAEiBY44e",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9084,
        dongName: "주안동",
      },
      {
        seq: 52655096,
        id: "68b7f2d01420ac13701782f7",
        roomTypeName: "오피스텔 • 단기",
        randomLocation: {
          lat: 37.490749,
          lng: 126.727723,
        },
        complexName: "노블렌스",
        roomTitle: "ll 단기가능 ll 반려동물가능 ll 복층 ll 허위x ll",
        roomDesc: "10층, 19.8m², 관리비 7만",
        priceTypeName: "월세",
        priceTitle: "80/48",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/AKWbyge7oOiyNe_MAhO8T",
          "https://d1774jszgerdmk.cloudfront.net/512/-5D189BsoIYFC-1kk5-_U",
          "https://d1774jszgerdmk.cloudfront.net/512/5MOedvwB_VE_F4nnNfKko",
          "https://d1774jszgerdmk.cloudfront.net/512/cGo2k5lN2MlVUZLD-AIPH",
          "https://d1774jszgerdmk.cloudfront.net/512/gXT1VHr_jvO6736GG4qSk",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52574930,
        id: "68b24a27f5e00c0332f199e9",
        roomTypeName: "오피스텔 • 단기",
        randomLocation: {
          lat: 37.496674,
          lng: 126.729918,
        },
        complexName: "라일플로리스",
        roomTitle: "ll 단기가능 ll 가성비최고 ll 신축급 ll 즉시입주가능 ll",
        roomDesc: "7층, 19.71m², 관리비 5만",
        priceTypeName: "월세",
        priceTitle: "60/47",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/9eegI02RaPFObFdOF15ww",
          "https://d1774jszgerdmk.cloudfront.net/512/FJM7EVqYikn9zv_o3zbUG",
          "https://d1774jszgerdmk.cloudfront.net/512/b3-7zGMQPMb9kqA91Y-tU",
          "https://d1774jszgerdmk.cloudfront.net/512/9O7qpfE-pSKaBekvosUhn",
          "https://d1774jszgerdmk.cloudfront.net/512/sG26cUbwA6_PXH-cDC6wg",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52877868,
        id: "68c8ddfe9e1b72097e3676f5",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.501298,
          lng: 126.72329,
        },
        complexName: "카이저",
        roomTitle: "부평시장역 역세권 깔끔한3룸 풀옵션 월세입니다",
        roomDesc: "4층, 68.34m², 관리비 10.5만",
        priceTypeName: "월세",
        priceTitle: "1000/125",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/4VzSmIqi8u4iyxdR5kUd2",
          "https://d1774jszgerdmk.cloudfront.net/512/jW8Z1n-XT4G4KsHb5hZsO",
          "https://d1774jszgerdmk.cloudfront.net/512/LqxDPTqlQDSazk8VrS6zz",
          "https://d1774jszgerdmk.cloudfront.net/512/8-y1rR8QbY9aAI5Qwu3cZ",
          "https://d1774jszgerdmk.cloudfront.net/512/pav9ADIbX29Y5LNdWEKBh",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52563360,
        id: "68b120f7aebb4f799a91a167",
        roomTypeName: "오피스텔 • 단기",
        randomLocation: {
          lat: 37.490749,
          lng: 126.727723,
        },
        complexName: "노블렌스",
        roomTitle:
          "++단기가능,몸만입주하세요,깔끔컨디션,가성비끝판왕,쓰리역세권,풀옵션++",
        roomDesc: "10층, 19.8m², 관리비 7만",
        priceTypeName: "월세",
        priceTitle: "80/48",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/AKWbyge7oOiyNe_MAhO8T",
          "https://d1774jszgerdmk.cloudfront.net/512/-5D189BsoIYFC-1kk5-_U",
          "https://d1774jszgerdmk.cloudfront.net/512/5MOedvwB_VE_F4nnNfKko",
          "https://d1774jszgerdmk.cloudfront.net/512/cGo2k5lN2MlVUZLD-AIPH",
          "https://d1774jszgerdmk.cloudfront.net/512/gXT1VHr_jvO6736GG4qSk",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52467953,
        id: "68aa7920c67adc7137c54be9",
        roomTypeName: "오피스텔 • 단기",
        randomLocation: {
          lat: 37.489705,
          lng: 126.728623,
        },
        complexName: "부평현대더로프트",
        roomTitle: "ll 단기가능 ll 부평역5분 ll 복층 ll 허위x ll",
        roomDesc: "8층, 23.25m², 관리비 5만",
        priceTypeName: "월세",
        priceTitle: "100/60",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/Fz6gLIU8JPcC38nyIqJVW",
          "https://d1774jszgerdmk.cloudfront.net/512/lfMpvWxo93YPFWYOzJNH9",
          "https://d1774jszgerdmk.cloudfront.net/512/HJ8P3uTN3s7ZcOjqHdWMa",
          "https://d1774jszgerdmk.cloudfront.net/512/k67ZmCm6e42EsJCsgVwpe",
          "https://d1774jszgerdmk.cloudfront.net/512/RG20A0gDockWnTjJthaUN",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
    ],
    premiumList: [],
    region: null,
    total: 317,
    limit: 24,
    hasMore: true,
    page: 1,
  },
  responseTime: "2025-09-23 09:35:55",
};

const newSection = document.createElement("section");
newSection.style.width = "30vw";
newSection.style.height = "100%";
newSection.style.display = "flex";
newSection.style.flexDirection = "column";
newSection.style.justifyContent = "center";
newSection.style.alignItems = "center";
newSection.style.border = "1px solid black";
document.body.appendChild(newSection);

data.result.roomList.forEach((v) => {
  const newArticle = document.createElement("article");
  newArticle.style.gap = "10px";
  newArticle.style.padding = "10px";
  newArticle.style.width = "100%";
  newArticle.style.height = "30%";
  newArticle.style.display = "flex";
  newArticle.style.flexDirection = "row";
  newArticle.style.justifyContent = "center";
  newArticle.style.alignItems = "center";
  newArticle.style.borderBottom = "1px solid black";

  newSection.appendChild(newArticle);

  const newPicture = document.createElement("picture");
  newPicture.style.width = "140px";
  newPicture.style.height = "140px";
  newArticle.appendChild(newPicture);

  const newImg = document.createElement("img");
  newImg.src = v.imgUrlList[0];
  newImg.style.width = "100%";
  newImg.style.height = "100%";
  newImg.style.objectFit = "cover";
  newPicture.appendChild(newImg);

  const newDiv = document.createElement("div");
  newDiv.style.width = "400px";
  newDiv.style.display = "flex";
  newDiv.style.flexDirection = "column";
  newArticle.appendChild(newDiv);

  const newH3 = document.createElement("h3");
  newH3.innerText = v.priceTitle + v.priceTypeName;
  newDiv.appendChild(newH3);

  const newSpan = document.createElement("span");
  newSpan.innerText = v.roomDesc + v.roomTitle;
  newDiv.appendChild(newSpan);

  const newButton = document.createElement("button");
  newButton.innerText = "플러스";
  newButton.style.color = "blue";
  newButton.style.width = "15%";
  newDiv.appendChild(newButton);
});
